apiVersion: v1
kind: Pod
metadata:
  name: websocket
spec:
  containers:
    - name: websocket
      image: 
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          hostPort: 80
